### ISSUE TITLE
Ща отчислю

### ISSUE THREAD

**Issue by Kirchberg** [NikLalkaGames/Unity-Almost-Alive-2d#1]
Тебя почему на паре нет? УУУУУУ

**Comment by Farhinarius** [comment]
Когда ехал, посрать захотелось
Решил вернутсья домой, покакать. Ну так дома и остался, на физ-ру приеду

**Comment by Farhinarius** [comment]
И да, понижу ка я тебя, чтобы тут не ахуевал с привилегий

**Comment by Kirchberg** [comment]
Это не я писал( Миша захватил ноут(((((

**Comment by Farhinarius** [comment]
Ну пизда Мише
